name: Extract and Upload RAR/ZIP to Google Drive

on:
  workflow_dispatch:
    inputs:
      rar_url:
        description: 'URL of the RAR or ZIP file'
        required: true
        type: string
      rar_password:
        description: 'Password for the RAR file (leave blank if not required)'
        required: false
        type: string

jobs:
  extract_and_upload:
    runs-on: ubuntu-latest  # Menjalankan workflow di runner Ubuntu

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Anda bisa menyesuaikan dengan versi Python yang digunakan

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pastikan Anda sudah memiliki file requirements.txt

    # Step 4: Install unrar and unzip
    - name: Install unrar and unzip
      run: sudo apt-get update && sudo apt-get install unrar unzip -y  # Install unrar dan unzip pada runner Ubuntu

    # Step 5: Create token.pickle from secret
    - name: Create token.pickle
      run: |
        echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > token.pickle  # Decode dan simpan token.pickle

    # Step 6: Download RAR or ZIP file
    - name: Download file
      run: |
        curl -L "${{ github.event.inputs.rar_url }}" -o downloaded.zip  # Download file menggunakan URL yang diinput

    # Step 7: Extract file (ZIP or RAR)
    - name: Extract file
      run: |
        mkdir extracted
        if [[ "${{ github.event.inputs.rar_url }}" == *.rar ]]; then
          # Jika file RAR, ekstrak dengan password jika ada
          if [ -z "${{ github.event.inputs.rar_password }}" ]; then
            unrar x downloaded.zip extracted/  # Tanpa password
          else
            unrar x -p"${{ github.event.inputs.rar_password }}" downloaded.zip extracted/  # Dengan password
          fi
        elif [[ "${{ github.event.inputs.rar_url }}" == *.zip ]]; then
          # Jika file ZIP, ekstrak tanpa password
          unzip downloaded.zip -d extracted/
        fi

    # Step 8: Upload extracted files to Google Drive
    - name: Upload to Google Drive
      run: |
        python upload_to_drive.py extracted/  # Jalankan skrip Python untuk mengupload file

    # Step 9: Clean up
    - name: Clean up
      run: |
        rm -rf extracted downloaded.zip  # Bersihkan file yang sudah tidak digunakan
